// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzLPGrr3V11mHhIVFk_friu47oR5LBsSs',
    appId: '1:821697692793:web:08bf27a9936c3287c400a8',
    messagingSenderId: '821697692793',
    projectId: 'leaf-link-1e912',
    authDomain: 'leaf-link-1e912.firebaseapp.com',
    databaseURL: 'https://leaf-link-1e912-default-rtdb.firebaseio.com',
    storageBucket: 'leaf-link-1e912.appspot.com',
    measurementId: 'G-Z9E1PLNTK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAliaU9VPVTLLvAqBitOol-lwfqlGxeDXs',
    appId: '1:821697692793:android:195ad8509aa13d7ac400a8',
    messagingSenderId: '821697692793',
    projectId: 'leaf-link-1e912',
    databaseURL: 'https://leaf-link-1e912-default-rtdb.firebaseio.com',
    storageBucket: 'leaf-link-1e912.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZk-iZ1r2SzRSFzYK3a32ZSREdmTEYlTg',
    appId: '1:821697692793:ios:c17ce8268d7a16f2c400a8',
    messagingSenderId: '821697692793',
    projectId: 'leaf-link-1e912',
    databaseURL: 'https://leaf-link-1e912-default-rtdb.firebaseio.com',
    storageBucket: 'leaf-link-1e912.appspot.com',
    iosBundleId: 'com.example.leaflink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZk-iZ1r2SzRSFzYK3a32ZSREdmTEYlTg',
    appId: '1:821697692793:ios:8ea4457d71afaca2c400a8',
    messagingSenderId: '821697692793',
    projectId: 'leaf-link-1e912',
    databaseURL: 'https://leaf-link-1e912-default-rtdb.firebaseio.com',
    storageBucket: 'leaf-link-1e912.appspot.com',
    iosBundleId: 'com.example.leaflink.RunnerTests',
  );
}
